# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               A Stack of TextEdit Files
tagline:             'a mess of notes'
description:         
url:                 http://dareneiri.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Daren Eiri
  url:               http://dareneiri.com
  email:             dareneiri@gmail.com

# Custom vars
version:             1.0.0
